# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    sudo apt-get install software-properties-common -y
    sudo apt-get install publican -y
    sudo add-apt-repository ppa:sascha-manns-h/publican -y
    sudo apt-get update
    sudo apt-get install --only-upgrade publican -y
    sudo apt-get install publican-xcom publican-manns -y
  displayName: 'Install dependencies'

- script: rake setup
  displayName: 'rake setup'

- script: bundle exec rake
  displayName: 'bundle exec rake'

- script: rake setup
  displayName: 'rake spec'

- task: PublishTestResults@2

#- task: PublishCodeCoverageResults@1
#  inputs:
#    codeCoverageTool: Cobertura
#    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
#   reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'