build:
  environment:
    ruby: '2.4.0'

  dependencies:
  # Runs before inferred commands
    before:
         - 'gem install bundler'
         - 'sudo apt-get update'
         - 'sudo apt-get install software-properties-common -y'
         - 'sudo apt-get install publican -y'
         - 'sudo add-apt-repository ppa:sascha-manns-h/publican -y'
         - 'sudo apt-get update'
         - 'sudo apt-get install --only-upgrade publican -y'
         - 'sudo apt-get install publican-xcom publican-manns -y'

checks:
    ruby:
        code_rating: true
        duplicate_code: true
        style_while_until_do: true
        style_signal_exception:
            enforced_style: semantic
        style_redundant_exception: true
        style_raise_args:
            enforced_style: exploded
        style_predicate_name: true
        style_comment_annotation: true
        rails_output: true

filter:
    excluded_paths:
        - 'spec/*'
        - 'docs/*'