# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "nokogiri", "~>1.8"
gem "parseconfig", "~>1.0"
gem "rainbow", "~>3.0"
gem "notifier", "~>0.5"
gem "xdg", "~>2.2"

gem "coveralls", "~>0.8", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-manns", "~>2.1", :group => [:development, :test]
gem "hoe-reek", "~>1.2", :group => [:development, :test]
gem "hoe-rubocop", "~>1.0", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "hoe", "~>3.17", :group => [:development, :test]
gem "rake", "~>12.3", :group => [:development, :test]
gem "rdoc", "~>6.0", :group => [:development, :test]
gem "bundler", "~>1.16", :group => [:development, :test]
gem "rspec", "~>3.7", :group => [:development, :test]
gem "rubocop", "~>0.57", :group => [:development, :test]

# vim: syntax=ruby
