# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "setup", "~>5.2"
gem "nokogiri", "~>1.6.6.2"
gem "parseconfig", "~>1.0.6"
gem "rainbow", "~>2.0.0"
gem "manns_shared", "~>1.0.0"
gem "notifier", "~>0.5.1"

gem "hoe-highline", "~>0.2", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "coveralls", "~>0.8", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe-deveiate", "~>0.7", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-doofus", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-manns", "~>1.0", :group => [:development, :test]
gem "hoe-reek", "~>1.0", :group => [:development, :test]
gem "hoe-rubocop", "~>0.1", :group => [:development, :test]
gem "hoe-travis", "~>1.2", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "hoe-yard", "~>0.1", :group => [:development, :test]
gem "hoe-seattlerb", "~>1.3", :group => [:development, :test]
gem "hoe", "~>3.14", :group => [:development, :test]
gem "ZenTest", "~>4.11", :group => [:development, :test]
gem "rake", "~>10.0", :group => [:development, :test]
gem "simplecov", "~>0.7", :group => [:development, :test]
gem "gem-release", "~>0.7", :group => [:development, :test]
gem "indexer", "~>0.3", :group => [:development, :test]
gem "reek", "~>3.3", :group => [:development, :test]
gem "manns_shared", "~>1.0", :group => [:development, :test]
gem "rainbow", "~>2.0", :group => [:development, :test]
gem "bundler", "~>1.10", :group => [:development, :test]
gem "parseconfig", "~>1.0", :group => [:development, :test]
gem "minitest", "~>5.8.1", :group => [:development, :test]
gem "rspec", "~>3.3", :group => [:development, :test]
gem "rubocop", "~>0.34", :group => [:development, :test]
gem "fpm", "~>1.4.0", :group => [:development, :test]
gem "bundler-audit", "~>0.4.0", :group => [:development, :test]

# vim: syntax=ruby
