name: Ruby Gem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        version: 2.7.x

    - name: Set up a Testingservice
      run: |
        gem install bundler
        bundle install --retry=3 --retry=4
        sudo apt-get install software-properties-common -y
        sudo apt-get install publican -y
        sudo add-apt-repository ppa:sascha-manns-h/publican -y
        sudo apt-get update
        sudo apt-get install --only-upgrade publican -y
        sudo apt-get install publican-xcom publican-manns -y
        rake setup bundle exec rake
        rake spec

    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
        OWNER: saigkill

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
